services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tup-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./DB:/app/DB
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: ["python","backend/manage.py","runserver","0.0.0.0:8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tup-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["npm","start"]