# Generated by Django 5.2.5 on 2025-10-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_matching1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('main_role', models.CharField(max_length=100)),
                ('sub_role', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.JSONField(default=list)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('participation', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='team',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='leader_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='matching_type',
            field=models.CharField(default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
