# Generated by Django 5.2.5 on 2025-09-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamMatching1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_role', models.CharField(max_length=100)),
                ('sub_role', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.JSONField(default=list)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('participation', models.IntegerField(default=0)),
            ],
        ),
    ]
