# Generated by Django 5.0.3 on 2025-10-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_matching1', '0002_user_team_is_finalized_team_leader_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinguser',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
