# Generated by Django 5.0.3 on 2025-10-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_matching1', '0003_alter_waitinguser_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='waitinguser',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='waitinguser',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='waitinguser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='waitinguser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_users', to='team_matching1.user'),
            preserve_default=False,
        ),
    ]
