# Generated by Django 5.0.3 on 2025-10-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_matching1', '0004_alter_user_options_remove_waitinguser_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='waitinguser',
            name='user',
        ),
        migrations.AddField(
            model_name='waitinguser',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='waitinguser',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='waitinguser',
            name='user_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
