# Generated by Django 5.0.3 on 2025-10-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_matching1', '0005_alter_user_options_remove_waitinguser_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAvoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_a', models.IntegerField()),
                ('user_b', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_a', 'user_b')},
            },
        ),
    ]
