# Generated by Django 5.2.1 on 2025-08-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_agree', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'feedbacks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rewarded',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_rewarded', models.BooleanField(null=True)),
                ('granted_at', models.DateTimeField(null=True)),
                ('user_name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'rewarded',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('matching_type', models.CharField(max_length=10)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10, null=True)),
                ('joined_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'team_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('main_role', models.CharField(max_length=50, null=True)),
                ('sub_role', models.CharField(max_length=50, null=True)),
                ('intro', models.TextField(null=True)),
                ('skills', models.JSONField(null=True)),
                ('keywords', models.JSONField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('participation', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('has_reward', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaitingUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('skills', models.JSONField()),
                ('main_role', models.CharField(max_length=100)),
                ('sub_role', models.CharField(max_length=100, null=True)),
                ('keywords', models.JSONField()),
                ('has_reward', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'waiting_users',
                'managed': False,
            },
        ),
    ]
